### ISSUE TITLE
The stream links don't work

### ISSUE THREAD

**Issue by Tdotsown** [dwbfox/kodi-ethiopian-tv#6] opened 2017-02-01 03:50 UTC
I have the links if you want.

**Comment by dwbfox** [comment] 2017-02-02 01:55
It looks like EBS has transitioned to a paid service, which may explain why the service went down so abruptly. I'm a bit hesitant to put non-public streams especially now that they're actually charging users money for it. What I might consider is to simply allow an interactive option to allow the user to supply their own streaming links. 

This issue is a duplicate of #4

**Closed as completed** 2017-02-02 01:56 UTC
